### ISSUE TITLE
preup(), postup() and related are not device-specific

### ISSUE THREAD

**Issue by lu-zero** [gentoo/netifrc#14]
in https://github.com/gentoo/netifrc/blob/master/init.d/net.lo.in#L563

I'd need to have a mean to use `ip neighbour` to get some ipv6 bridge configuration working fine and I thought about using a `postup_br0` to just issue the necessary commands.

To my surprise the hook seems generic.

**Comment by robbat2** [comment]
The long-standing examples for preup/postup usage explicitly document using a case statement to detect which interface(s) you are running them on, if you need to do interface-specific actions.

If we have preup_$IFACE, would it run before or after a generic preup? How would you write it for generated interfaces that didn't have explicit config blocks before?

**Comment by vapier** [comment]
could go the preup_pre_$IFACE and preup_post_$IFACE route ;)

why don't we just make the default preup() function run preup_$IFACE().  that way there is no debate as to which runs first: if you define your own preup, you're now responsible for running preup_$IFACE yourself.

**Comment by lu-zero** [comment]
@robbat2 where are those examples?

**Comment by robbat2** [comment]
See the net.example.
#postdown() {
#       # Enable Wake-On-LAN for every interface except for lo
#       # Probably a good idea to set ifdown="no" in /etc/conf.d/net
#       # as well ;)
#       [ "${IFACE}" != "lo" ] && ethtool -s "${IFACE}" wol g
#       # Return 0 always
#       return 0
#}

Here's another one from my box:
preup_ipv6_dad() {
	einfo "Disabling IPv6 DAD on $1"
	sysctl -w net.ipv6.conf.${1}.dad_transmits=0
}
postup() {
	case $IFACE in
		enp13s0f0|enp13s0f1|bond0|team0) preup_ipv6_dad $IFACE ;;
	esac
}

**Comment by robbat2** [comment]
No further response, closing
